[[configs]]
name = "BASELINE"
gpgpu_sim_config = "/pool/connor/accel-sim-framework/gpu-simulator/gpgpu-sim/configs/tested-cfgs/SM7_QV100/gpgpusim.config"
accel_sim_config = "/pool/connor/accel-sim-framework/gpu-simulator/configs/tested-cfgs/SM7_QV100/trace.config" 

[[configs]]
name = "VELRR_ONLY"
gpgpu_sim_config = "/pool/connor/accel-sim-framework/gpu-simulator/gpgpu-sim/configs/tested-cfgs/VELRR_ONLY/gpgpusim.config"
accel_sim_config = "/pool/connor/accel-sim-framework/gpu-simulator/configs/tested-cfgs/VELRR_ONLY/trace.config" 

[[configs]]
name = "VELRR_VELRU_L1"
gpgpu_sim_config = "/pool/connor/accel-sim-framework/gpu-simulator/gpgpu-sim/configs/tested-cfgs/VELRR_VELRU_L1/gpgpusim.config"
accel_sim_config = "/pool/connor/accel-sim-framework/gpu-simulator/configs/tested-cfgs/VELRR_VELRU_L1/trace.config" 

[[configs]]
name = "VELRR_VELRU_L1_L2"
gpgpu_sim_config = "/pool/connor/accel-sim-framework/gpu-simulator/gpgpu-sim/configs/tested-cfgs/VELRR_VELRU_L1_L2/gpgpusim.config"
accel_sim_config = "/pool/connor/accel-sim-framework/gpu-simulator/configs/tested-cfgs/VELRR_VELRU_L1_L2/trace.config" 

[[configs]]
name = "VELRU_L1"
gpgpu_sim_config = "/pool/connor/accel-sim-framework/gpu-simulator/gpgpu-sim/configs/tested-cfgs/VELRU_L1/gpgpusim.config"
accel_sim_config = "/pool/connor/accel-sim-framework/gpu-simulator/configs/tested-cfgs/VELRU_L1/trace.config" 

[[configs]]
name = "VELRU_L1_L2"
gpgpu_sim_config = "/pool/connor/accel-sim-framework/gpu-simulator/gpgpu-sim/configs/tested-cfgs/VELRU_L1_L2/gpgpusim.config"
accel_sim_config = "/pool/connor/accel-sim-framework/gpu-simulator/configs/tested-cfgs/VELRU_L1_L2/trace.config" 
